FROM nginx
# Removing default html and then copying our html in the below 2 steps
RUN rm -rf
# Files should be available in current directory where Dockerfile exist
# COPY index.html /usr/share/nginx/html/index.html
COPY qi/ /usr/share/nginx/html/