FROM almalinux:8
# copying hello.txt to tmp folder in the below line
ADD hello.txt /tmp/
ADD https://raw.githubusercontent.com/sivadevopsdaws74s/dockerfiles/master/commands.MD /tmp/c:\Users\user\Downloads\sample-1.tar
ADD sample-1.tar /tmp/
